version: '2'

services:
  db:
    image: mariadb
    restart: always
    volumes:
      - /home/murray/nextcloud/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=nextcloud
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  app:
    image: nextcloud
    restart: always
    ports:
      - 80:80
    links:
      - db
    volumes:
      - /home/murray/nextcloud/root:/var/www/html
      - /home/murray/nextcloud/data:/var/www/html/data
